### ISSUE TITLE
webdav and/or debian client ?

### ISSUE THREAD

**Issue by combaudon** [cozy/cozy-sync#73]
Hi,
When do you plan to enhance Webdav or develop a linux (debian, .. or others) client ?

**Comment by aenario** [comment]
Hi @combaudon,

We have an (alpha) desktop client 
http://github.com/cozy/cozy-desktop
http://files.cozycloud.cc/cozy-desktop-0.3.0-i386.deb
http://files.cozycloud.cc/cozy-desktop-0.3.0-amd64.deb

For now, it only sync from cozy to the desktop, any change made locally will be overriden by a change on the server. Two way sync should be available next month or so. Feedbacks are very welcome !

We focus our development effort on this custom-made client to offer the same experience on all OSes and because it will allow us to propose offline cozy functionalities in the future. So we wont be working on webdav support in the foreseeable future. However, the package jsDAV, which cozy-sync is based on has support for WebDAV, and if someone wants to contribute a cozy files backend for it, we will provide feedbacks and assistance.

**Comment by combaudon** [comment]
Many thanks for your quick answer.

Url is https://github.com/cozy-labs/cozy-desktop not
https://github.com/cozy/cozy-desktop which is 404 ;o)
I'm going to try it.
Christian

**Comment by combaudon** [comment]
Bonjour,
Effectivement, c'est OK maintenant.
Par contre bug:
Tout mes fichiers synchronisés font le même poid (20,8 Ko) et sont illisibles (.ODT, .PDF, .DOC) excepté les fichiers .JPG qui ont conservé aussi leur libellé mais à l'ouverture sont tous les mêmes!
En fait il s'agit d'un .JPG qui fait 20,8 Ko et que j'avais déposé dans un répertoire de "FILE" puis ensuite transféré via COZYCLOUD dans "PHOTO".
Cdlt


... do you want me to write it in english ?!

**Comment by combaudon** [comment]
Bonjour,
J'ai toujours le même bug que dans mon message du 26/03
ainsi qu'un bug supplémentaire:
Si mon terminal est déjà lancé avec l"instruction "cozy-desktop sync", aucune modification que je fais en ligne n'est reprise dans mes répertoires en local.
Il faut que je relance mon terminal et "cozy-desktop sync" après la modification effectuée en ligne

Et les nouveaux fichiers en local font encore et toujours le même poids de 20,8 ko ;o(

**Comment by aenario** [comment]
Bonjour @combaudon, désolé d'avoir laissé passer ton bug.
Je viens d'ouvrir une issue sur le repo concerné :  https://github.com/cozy-labs/cozy-desktop/issues/86 , c'est plus simple à suivre pour nous. 

Je ferme l'issue ici.
